image: maven:3.6.3-jdk-8

stages:
    - test
    - build

include:
    - template: Security/SAST.gitlab-ci.yml

build:
    stage: build
    script:
        - time mvn package appassembler:assemble -D skipTests
        - mv target/dbgit dbgit
    only:
        refs:
            - master
    artifacts:
        expire_in: never
        paths:
            - dbgit
test:
    stage: test
    script:
        - time mvn test

cache:
  paths:
    - .m2/repository
