env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
assets:
  pgSecret.txt: rocket-3/dbgit-test#pgSecret.txt
  gitSecret.txt: rocket-3/dbgit-test#gitSecret.txt
merge:
  script: |-
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install package appassembler:assemble -D skipTests --batch-mode --quiet
    chmod u+r+x target/dbgit/bin/dbgit
    mvn test -Dtest=*selfTest,*DbGitIntegrationTestBasic* --batch-mode
deploy:
  script: |-
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install package appassembler:assemble -D skipTests --batch-mode --quiet
    chmod u+r+x target/dbgit/bin/dbgit
    mvn test -Dtest=*selfTest,*DbGitIntegrationTestBasic* --batch-mode
