env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
assets:
  pgSecret.txt: rocket-3/dbgit-test#pgSecret.txt
  gitSecret.txt: rocket-3/dbgit-test#gitSecret.txt
merge:
  script: |-
    java -version --batch-mode
    mvn -version --batch-mode
    mvn clean install package appassembler:assemble -D skipTests --batch-mode
deploy:
  script: |-
    java -version
    mvn -version
    mvn clean install package appassembler:assemble -D skipTests --batch-mode
    mvn test -Dtest=*selfTest,*DbGitIntegrationTestBasic* --batch-mode
